require('general')
require('dashboard-header')
require('plugins')
require('color')
require('lsp')
require('mappings')

require('plugin-cmp')
require('plugin-easymotion')
require('plugin-indentline')
require('plugin-lualine')
require('plugin-neoterm')
require('plugin-nvim-tree')
require('plugin-prettier')
require('plugin-symbols-outline')
require('plugin-vim-submode')
require('plugin-vim-terraform')
