require('general')
require('plugins')
require('color')
require('lsp')
require('mappings')

require('plugin-ctrlp')
require('plugin-easymotion')
require('plugin-indentline')
require('plugin-neoterm')
require('plugin-nerdtree')
require('plugin-prettier')
require('plugin-vim-submode')
require('plugin-cmp')
require('plugin-symbols-outline')
